### ISSUE TITLE
`npm run build` fails on Windows

### ISSUE THREAD

**Issue by justinyoo** [Azure/APICenter-Portal-Starter#18]
On Windows, when I run the command `npm run build`, it fails like:

![image](https://github.com/Azure/APICenter-Portal-Starter/assets/1538528/4afe830d-5540-402c-a57e-7de2900a8282)

However, on Ubuntu (or WSL) or MacOS, the same command `npm run build` doesn't fail.

I tested it on node version `18.x` and `20.x`.

**Comment by pierceboggan** [comment]
@justinyoo - Can you still reproduce this? I can't using the latest build.

**Comment by pierceboggan** [comment]
I tried this again today, but can't reproduce. Closing as no reproduction. Please reopen if this is still happening for you!
