### ISSUE TITLE
Unable to deploy Azure API Center Portal using AZD

### ISSUE THREAD

**Issue by sushantgujar0410** [Azure/APICenter-Portal-Starter#19]
Getting error message when tried to deploy API center to azure using AZD tool

'error executing step command 'deploy --all': failed deploying service 'staticapp-portal': failed deploying static web app: swa deploy: exit code: 1, stdout: , stderr: npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.'

**inflight** package has been deprecated. #https://www.npmjs.com/package/inflight

![image (1)](https://github.com/Azure/APICenter-Portal-Starter/assets/172467788/ff4b7818-c779-4825-9f60-0fee5ede043f)

**Comment by justinyoo** [comment]
@pierceboggan Would you please be able to take on this?

**Comment by sthirthala** [comment]
@sushantgujar0410  can you try deploying using Static Web apps as described here. And let me know if you still face issue.

https://github.com/Azure/APICenter-Portal-Starter?tab=readme-ov-file#manual-deployment-to-azure-static-web-apps

**Comment by sthirthala** [comment]
if the above does not work, I can setup a call

**Comment by sushantgujar0410** [comment]
@sthirthala : I follow the steps mentioned []([](https://github.com/Azure/APICenter-Portal-Starter?tab=readme-ov-file#manual-deployment-to-azure-static-web-apps))
It works locally as expected but when i tried deploy it to azure portal it throws above error

.

**Comment by sushantgujar0410** [comment]
> if the above does not work, I can setup a call

I followed the instructions provided in the documentation, but unfortunately, it did not yield the desired results. Could we schedule a call at your convenience to discuss this further? Please note that I am located in the IST time zone. Thank you for your assistance.

**Comment by sushantgujar0410** [comment]
> @pierceboggan Would you please be able to take on this?

@pierceboggan :  can someone else investigate this matter? Thanking you in advance.

**Comment by sushantgujar0410** [comment]
@juliajuju93 @juliamuiruri4 can you please help me here with this issue. thanks in advance.

**Comment by pierceboggan** [comment]
Hi - from following up with some folks offline, it seems this issue was resolved? I'm marking as closed, but if it's still happening please reopen and tag our team. Thank again for logging your feedback!
