### ISSUE TITLE
Unable to fetch APIs from API center portal

### ISSUE THREAD

**Issue by austinlee0527** [Azure/APICenter-Portal-Starter#23]
I have deployed the API center portal to local and Azure Static Web App. After login to the portal, I am unable to fetch APIs, got CORS error.

Request URL: https://****.data.eastus.azure-apicenter.ms/workspaces/default/apis
Origin: https://localhost:5173

![image](https://github.com/Azure/APICenter-Portal-Starter/assets/20919202/8d7f85ff-479f-4454-b231-b36ded4d2729)

**Comment by emilioc7** [comment]
Same issue for me. Followed app registration steps from the repo.


![API-Data-Center-Issue](https://github.com/Azure/APICenter-Portal-Starter/assets/33851624/d9b25dda-f499-4309-a08c-d5802c0e4ab6)

**Comment by pierceboggan** [comment]
@austinlee0527 @emilioc7 - Thanks for reporting this issue! We've identified a fix and are working on a rollout now. I'll update this thread once the rollout completes.

**Comment by pierceboggan** [comment]
@austinlee0527 @emilioc7 - The fix for this should now be rolled out to all regions! I'm closing this issue, but feel free to re-open and tag us if you can still reproduce.

Thanks so much for your feedback!

**Comment by emilioc7** [comment]
Thanks @pierceboggan, it's working now.

**Comment by ArunKatoch** [comment]
I am facing the same issue Access to fetch at 'https://xxxxxxxxxx.data.westeurope.azure-apicenter.ms/workspaces/default/apis' from origin 'https://127.0.0.1:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
