### ISSUE TITLE
No API's shown in portal after I login

### ISSUE THREAD

**Issue by maikvandergaag** [Azure/APICenter-Portal-Starter#24]
When I login the page is reloaded with no API's and a error in the devtools:

![image](https://github.com/Azure/APICenter-Portal-Starter/assets/9531411/09d138b4-8993-4ab4-91cf-dc0b778ce686)

Permissions are configured correctly.

**Comment by pierceboggan** [comment]
@maikvandergaag - Thanks for reporting this issue! We've identified a fix and are working on a rollout now. I'll update this thread once the rollout completes.

**Comment by pierceboggan** [comment]
@maikvandergaag  The fix for this should now be rolled out to all regions! I'm closing this issue, but feel free to re-open and tag us if you can still reproduce.

Thanks so much for your feedback!
