### ISSUE TITLE
API Listing is blocked by CORS - policy

### ISSUE THREAD

**Issue by brendonbouwer** [Azure/APICenter-Portal-Starter#25]
No APIs are displayed on the portal due to the API Listing being blocked by a CORS - policy. Please refer to the error below:

"Access to fetch at 'https://xxxx.xxxx.xxxxx/workspaces/default/apis' from origin 'https://xxxx.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."

![image](https://github.com/Azure/APICenter-Portal-Starter/assets/175215559/1162108a-a00d-4562-b200-87607ef4d9dd)

**Comment by pierceboggan** [comment]
@brendonbouwer - Thanks for reporting this issue! We've identified a fix and are working on a rollout now. I'll update this thread once the rollout completes.

**Comment by brendonbouwer** [comment]
Thank you @pierceboggan. Appreciated

**Comment by pierceboggan** [comment]
@brendonbouwer The fix for this should now be rolled out to all regions! I'm closing this issue, but feel free to re-open and tag us if you can still reproduce.

Thanks so much for your feedback!

**Comment by brendonbouwer** [comment]
Hi @pierceboggan , thanks for the update however it is still returning the error below:

"Access to fetch at 'https://xxxx.xxxx.xxxxx/workspaces/default/apis' from origin 'https://xxxx.net/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."

![image](https://github.com/user-attachments/assets/9574a61d-16e2-41aa-9167-54e5395a70dc)

**Comment by Asim-21** [comment]
I am getting the same error "has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

![image](https://github.com/user-attachments/assets/fc14aa51-e58e-4804-a6e7-d168bce48553)
